# Generated by Django 4.2.15 on 2024-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0002_alter_category_options_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=200),
        ),
    ]
