# Generated by Django 4.2.15 on 2024-09-06 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Store", "0004_alter_book_category_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="rate_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
