# Generated by Django 4.2.15 on 2024-09-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0005_rating_rate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
        migrations.AddField(
            model_name="book",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
