# Generated by Django 4.2.15 on 2024-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0006_book_image_book_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="average_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
